"""Inputs of the release qualification lane (validation.md, "Release qualification lane").

Every input is generated here from its definition; nothing is read from local evidence. `check()` proves
that the generated bytes equal the inputs recorded by earlier sessions (recorded-inputs.json): each gate
case by its SHA-256, the tree-comparison dataset and the incremental scripts by an aggregate digest.
Stdlib only; starts no program.
"""
import hashlib
import json
import math
import random
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE.parent))
from corpus import read_corpus  # noqa: E402

RECORDED = json.loads((HERE / "recorded-inputs.json").read_text(encoding="utf-8"))
MIB = 1048576

# (prefix, unit, suffix) of the repeated families; the input is prefix + unit * k + suffix (UTF-8, LF).
FAMILY = {
    "B5-01-prefix": ("x = ", "+f([)", "\n"),
    "B5-01-minus": ("", "-f(-)", "\n"),
    "B5-01-aa": ("x = ", "{a:@*}<", "\n"),
    "B5-02-call": ("print ", "f([)", "\n"),
    "B5-02-sep": ("print ", ",+*", "\n"),
    "B502X": ("x = ", "-f(-)", "\n"),
    "A5-01": ("print ", "a;", "\n"),
    "A5-01-number": ("print ", "1;", "\n"),
    "A501J": ("print ", "a ", "\n"),
    "KL2-plusstar": ("x = ", "+*", "\n"),
    "Q-INDEX-MEMBER": ("x = a", "[b.", "\n"),
    "Q-NEG-PAREN-IDX": ("x = ", "-(-[", "\n"),
    "Q-PAREN-NEG": ("x = ", "(-", "\n"),
    "Q-TRY": ("", "try\n", ""),
    "Q-PAREN": ("x = ", "(", "\n"),
    "Q-ARR": ("x = ", "[", "\n"),
    "QV-MEMBER-CHAIN": ("x = a", ".b", "\n"),
    "QV-INDEX-CHAIN": ("x = a", "[1]", "\n"),
    "QV-CALL-CHAIN": ("x = f", "(1)", "\n"),
    "QV-MIXED-CHAIN": ("x = a", ".b(1)[2]", "\n"),
    "QV-METH": ("x = a", ".b(1)", "\n"),
    "QV-STMT": ("a", ".b(1)", "\n"),
    "QV-ATTR": ("x = a", ".b@c", "\n"),
    "QV-OPTIONAL": ("x = a", "?.b?(1)?[2]", "\n"),
}
# CANCEL set extras (resume-07): an AA-in-AA family with a colon suffix.
FAMILY["SW-z203d207bk3a20-7ba3a402a7d3c-colon"] = ("z = {k: ", "{a:@*}<", ": print 1\n")
FAMILY["REVB-aaz-colon"] = ("z = {k: ", "{a:@*}<", ": print 1\n")

NESTED_IF_BLOCK = "if a then\n" * 200 + "x = 1\n" + "end if\n" * 200
# 1 MiB set (protocol v3 LARGE-INPUT): k = ceil((1 MiB - prefix - suffix) / unit).
LARGE = {
    "L-AAZ-colon": ("z = {k: ", "{a:@*}<", ": print 1\n"), "L-AAZ-nl": ("z = {k: ", "{a:@*}<", "\n"),
    "L-AAZ-minus": ("z = {k: ", "-f(-)", ": print 1\n"), "L-PREFIX": ("x = ", "+f([)", "\n"),
    "L-MINUS": ("", "-f(-)", "\n"), "L-AA": ("x = ", "{a:@*}<", "\n"), "L-CALL": ("print ", "f([)", "\n"),
    "L-SEP": ("print ", ",+*", "\n"), "L-WHILE": ("", "while a\n+\n", ""), "L-FOREACH": ("", "for each a in b\n", ""),
    "L-ANON": ("", "x = function()\n", ""), "V-FLAT": ("", "x = a + 1\n", ""), "V-ARRAY": ("x = [", "1, ", "1]\n"),
    "V-LONGEXPR": ("x = 1", " + a * 2", "\n"), "V-CALLS": ("", "f(a, b[1], c.d)\n", ""),
    "V-PRINT": ("print ", "a;", "\n"), "V-NESTED-IF": ("", NESTED_IF_BLOCK, ""),
}
LARGE_MALFORMED = ["L-AAZ-colon", "L-AAZ-nl", "L-AAZ-minus", "L-PREFIX", "L-MINUS", "L-AA", "L-CALL", "L-SEP", "L-WHILE",
                   "L-FOREACH", "L-ANON"]
LARGE_VALID = ["V-FLAT", "V-ARRAY", "V-LONGEXPR", "V-CALLS", "V-PRINT", "V-NESTED-IF"]
# VALID-PARSE controls (resume-07): k = max(1, (n - prefix - suffix) // unit) for n in {4, 16, 64, 256} KiB.
VALID = {"flat-assign": ("", "x = a + 1\n", ""), "array": ("x = [", "1, ", "1]\n"), "aa": ("x = {", "a: 1, ", "b: 2}\n"),
         "long-expr": ("x = 1", " + a * 2", "\n"), "calls": ("", "f(a, b[1], c.d)\n", ""),
         "nested-if": ("", NESTED_IF_BLOCK, "")}
# R7 structural sweep: 9 contexts x 10 units x 3 ends.
SWEEP_CONTEXTS = ["x = ", "print ", "return ", "if ", "while ", "y = [", "z = {k: ", "f(", "? "]
SWEEP_UNITS = ["+f([)", "-f(-)", "{a:@*}<", "f([)", ",+*", "+*", "f(*", "2^*", "[1,", "(not)",
               ") else "]  # a block keyword after each malformed piece (Session 05-7 review B2-01)
SWEEP_ENDS = [("\n", "nl"), (": print 1\n", "colon"), ("", "eof")]


def slug(text):
    return "".join(ch if ch.isalnum() else f"{ord(ch):02x}" for ch in text)


def repeated(prefix, unit, k, suffix):
    return (prefix + unit * k + suffix).encode()


def generate(case_id):
    """Bytes of one named case. Formats: <family>-k<k>, <large>-1MiB, VALID-<family>-<kb>k, SW-<ctx>-<unit>-<end>-k<k>."""
    if case_id.endswith("-1MiB"):
        name = case_id[:-5]
        prefix, unit, suffix = LARGE[name]
        k = 308 if name == "V-NESTED-IF" else math.ceil((MIB - len(prefix) - len(suffix)) / len(unit))
        return repeated(prefix, unit, k, suffix)
    if case_id.startswith("VALID-"):
        family, kb = case_id[6:].rsplit("-", 1)
        n = int(kb[:-1]) * 1024
        prefix, unit, suffix = VALID[family]
        k = max(1, n // len(unit)) if family == "nested-if" else max(1, (n - len(prefix) - len(suffix)) // len(unit))
        return repeated(prefix, unit, k, suffix)
    family, k = case_id.rsplit("-k", 1)
    if family in FAMILY:
        prefix, unit, suffix = FAMILY[family]
        return repeated(prefix, unit, int(k), suffix)
    if family.startswith("SW-"):
        for ctx in SWEEP_CONTEXTS:
            for unit in SWEEP_UNITS:
                for end, tag in SWEEP_ENDS:
                    if family == f"SW-{slug(ctx)}-{slug(unit)}-{tag}":
                        return repeated(ctx, unit, int(k), end)
    raise KeyError(case_id)


def sweep_families():
    return [(f"SW-{slug(c)}-{slug(u)}-{tag}", c, u, e) for c in SWEEP_CONTEXTS for u in SWEEP_UNITS for e, tag in SWEEP_ENDS]


def tree_compare():
    """The 2,811 inputs of the tree comparison (resume-07 r07_trees.py): corpus, samples, random PRINT, combinations.
    Returns (name, bytes, valid) with valid None where only the reference parser decides."""
    corpus, duplicates = read_corpus()
    assert not duplicates
    items = [(f"corpus:{n}", t["input"], ":error" not in t["attrs"]) for n, t in corpus.items()]
    items += [(f"sample:{p.name}", p.read_bytes(), True) for p in sorted((ROOT / "test/samples").glob("*.brs"))]
    rng = random.Random(7)
    atoms = ["a", "1", '"s"', "f(1)", "a.b", "a[1]", "(a)", "-a", "not a", "a + b", "a * b ^ c", "[1, 2]", "{a: 1}",
             "f()", "a@b", "a?.b", "x.y(1)[2]", "2^-3"]
    seps = [" ", "; ", ", ", ";", ",", " ; ", ""]
    for i in range(1500):
        its = [rng.choice(atoms) for _ in range(rng.randint(1, 6))]
        s = rng.choice(["print ", "? ", "print"]) + "".join(it + rng.choice(seps) for it in its)
        if rng.random() < 0.3:
            s = f"if a then {s}" if rng.random() < 0.5 else f"sub main()\n  {s}\nend sub"
        items.append((f"randprint:{i}", (s.rstrip() + "\n").encode(), None))
    for ctx in ("x = ", "print ", "return ", "if ", "while ", "y = [", "z = {k: ", "f(", "? "):
        for unit in ("+f([)", "-f(-)", "{a:@*}<", "f([)", ",+*", "+*", "f(*", "2^*", "[1,", "(not)"):
            for end in ("", "\n", ": print 1\n", "\nend\n"):
                for k in (3, 12, 40):
                    items.append((f"combo:{ctx!r}|{unit!r}|{end!r}|{k}", (ctx + unit * k + end).encode(), False))
    return items


# RECOVERY-LOCALITY (Session 05-7 review A-01): every single-line mutant of these files.
LOCALITY_BASES = ["test/samples/program.brs", "test/samples/compact.brs", "test/highlight/highlights.brs"]
MUTATIONS = {
    "paren": lambda line: line + " (",
    "plus": lambda line: line + " +",
    "dropc": lambda line: line[:-1],
    "comma": lambda line: line + ",",
    "eqeq": lambda line: line.replace("=", "= =", 1),
    "brack": lambda line: line + " [",
    "quote": lambda line: line + ' "x',
    "rparen": lambda line: line[: len(line) // 2] + ")" + line[len(line) // 2:],
    "dot": lambda line: line + ".",
    "brace": lambda line: line + " {",
}


def locality_mutants():
    """(name, bytes, mutated row): each mutation that changes a non-blank, non-comment line of a base file."""
    out = []
    for base in LOCALITY_BASES:
        lines = (ROOT / base).read_text(encoding="utf-8").split("\n")
        for i, line in enumerate(lines):
            if not line.strip() or line.lstrip().startswith(("'", "rem", "REM")):
                continue
            for name, mutate in MUTATIONS.items():
                changed = mutate(line)
                if changed != line:
                    data = "\n".join(lines[:i] + [changed] + lines[i + 1:]).encode("utf-8")
                    out.append((f"{Path(base).stem}_{i}_{name}", data, i))
    return out


def _cli_to_bytes(text, edit):
    pos, deleted, inserted = edit.split(" ", 2)
    row, col = (int(x) for x in pos.split(","))
    lines = text.split(b"\n")
    return sum(len(line) + 1 for line in lines[:row]) + col, int(deleted), inserted.encode("utf-8")


def incremental():
    """The 28 edit scripts of INCREMENTAL-REPAIR (resume-07 r07_incr.py): (name, base, edit lines)."""
    import check_incremental as ci
    corpus, _ = read_corpus()
    raw = []
    for name, (base_name, edits) in sorted(ci.SCRIPTS.items()):
        raw.append((f"W10-{name}", corpus[base_name]["input"], edits, "cli"))
    for name, edits in sorted(ci.SPIKE.items()):
        raw.append((f"W10-{name}", ci.SPIKE_BASE, edits, "cli"))
    a5 = generate("A5-01-k04000")
    raw.append(("R6-aa-error", b"x = {a: [1, 2], b: 3}\n", [(8, 0, b"@*")], "bytes"))
    raw.append(("R6-block-error", b"sub main()\n print a; f([1])\nend sub\n", [(26, 1, b"")], "bytes"))
    raw.append(("R6-prefix-error", b"x = -f([1])\n", [(5, 0, b"*")], "bytes"))
    raw.append(("R6-print-middle", a5, [(4006, 1, b"f(1)")], "bytes"))
    raw.append(("PRINT-eof-error", a5, [(len(a5) - 1, 0, b"+*")], "bytes"))
    raw.append(("PRINT-middle-error", a5, [(len(a5) // 2, 0, b"+*")], "bytes"))
    b5 = generate("B5-01-prefix-k00200")
    raw.append(("B5-01-prefix-append", b5, [(len(b5) - 1, 0, b"+f([)")], "bytes"))
    prog = b"".join(p.read_bytes() for p in sorted((ROOT / "test/samples").glob("*.brs")) if b"\r" not in p.read_bytes())
    prog = prog.rstrip(b"\n") + b"\n"
    big = prog * max(1, 100_000 // len(prog) + 1)
    rng = random.Random(1234)
    line_ends = [i for i, ch in enumerate(big) if ch == 10]
    for n in (1, 10, 100):
        picks = sorted(rng.sample(line_ends, n), reverse=True)
        raw.append((f"scattered-{n:03d}", big, [(p, 0, b" + *") for p in picks], "bytes"))
    out = []
    for name, base, edits, kind in raw:
        text, lines = base, []
        for e in edits:
            off, deleted, inserted = _cli_to_bytes(text, e) if kind == "cli" else e
            lines.append(f"{off} {deleted} {inserted.hex() or '-'}")
            text = text[:off] + inserted + text[off + deleted:]
        out.append((name, base, ("\n".join(lines) + "\n").encode()))
    return out


def check():
    """Regenerate every recorded input; return a list of mismatches (empty = exact reproduction)."""
    bad = [cid for cid, digest in RECORDED["cases"].items() if hashlib.sha256(generate(cid)).hexdigest() != digest]
    h = hashlib.sha256()
    items = tree_compare()
    for _, data, _ in items:
        h.update(hashlib.sha256(data).digest())
    if len(items) != RECORDED["tree_compare_count"] or h.hexdigest() != RECORDED["tree_compare_aggregate"]:
        bad.append("tree_compare")
    h = hashlib.sha256()
    for name, base, edits in sorted(incremental()):
        h.update(f"{name}.brs".encode())
        h.update(hashlib.sha256(base).digest())
        h.update(hashlib.sha256(edits).digest())
    if h.hexdigest() != RECORDED["incremental_aggregate"]:
        bad.append("incremental")
    h = hashlib.sha256()
    for name, data, row in locality_mutants():
        h.update(f"{name}:{row}".encode())
        h.update(hashlib.sha256(data).digest())
    if h.hexdigest() != RECORDED.get("locality_aggregate"):
        bad.append("locality")
    return bad


if __name__ == "__main__":
    mismatches = check()
    print("recorded inputs reproduced" if not mismatches else f"MISMATCH: {mismatches}")
    sys.exit(1 if mismatches else 0)
