' Roles on chains of member, attribute, index and call expressions, and on optional access
' (W11 rows; S07-M03). Expected roles follow the W11 table, not a query's output.
x = a.b.c
'   ^ variable
'    ^ punctuation.delimiter
'     ^ property
'       ^ property
m.total = total
' <- variable.builtin
' ^ property
'         ^ variable
z = n@title@lang
'   ^ variable
'    ^ operator
'     ^ attribute
'           ^ attribute
w = a?.b?@c
'    ^ operator
'      ^ property
'       ^ operator
'         ^ attribute
v = a.b(1).c(2)[3].d
'     ^ function
'          ^ function
'              ^ punctuation.bracket
'                  ^ property
t = CreateObject("x").Count()
'   ^ function.builtin
'                     ^ function
s = f(1)(2).g
'   ^ function
'           ^ property
a.b.c = 1
' <- variable
' ^ property
'   ^ property
a.b(1)[2].c(3)
' <- variable
' ^ function
'         ^ function
p = (a).b
'       ^ property
r = a?.b.c?[0]?(1).d
'      ^ property
'        ^ property
'         ^ operator
'             ^ operator
'                  ^ property
print a.b; n@c
'       ^ property
'            ^ attribute
q = a.b@c.d(1)
'     ^ property
'       ^ attribute
'         ^ function
